[ -n "${_ETC_ZFSBOOTMENU_CONF:-}" ] && return
readonly _ETC_ZFSBOOTMENU_CONF=1
export import_policy=force
export menu_timeout="${ZBM_MENU_TIMEOUT:--1}"
export HAS_REFRESH=1
export HAS_DISABLED=1
export HAS_BORDER=1
unset HAS_COLUMN
