#!/bin/sh /etc/rc.common
START=19
USE_PROCD=0

start() {
	mkdir -p /run/zbm-progress
	: > /run/zbm-progress/zbm-kcl-setup.start
	/usr/bin/zbm-kcl-apply >/tmp/zbm-kcl-apply.log 2>&1 || true
	: > /run/zbm-progress/zbm-kcl-setup.done
}
